### ISSUE TITLE
undefined instead of a comma in the title of a note

### ISSUE THREAD

**Issue by repetitioestmaterstudiorum** [akosbalasko/yarle#130]
**_(first of all, thanks a lot for creating this script - it's incredibly useful and valuable!!)_**

I converted a note from Evernote with the title "** Waiting, for inspiration will come" and it resulted in "** Waitingundefined for inspiration will come" in the .md file (opened with Obsidian 0.9.20).

Config:
{
	"enexSource": "<mysecretpath>file.enex",
	"outputDir": "/md-files",
	"isMetadataNeeded": true,
	"isNotebookNameNeeded": true,
	"isZettelkastenNeeded": false,
	"plainTextNotesOnly": false,
	"skipLocation": false,
	"skipCreationTime": false,
	"skipUpdateTime": false,
	"skipSourceUrl": false,
	"skipWebClips": false,
	"skipTags": false,
	"outputFormat": "StandardMD",
	"skipEnexFileNameFromOutputPath": false
}

Command I ran: npx -p  yarle-evernote-to-md yarle  --configFile ./config.json

Node version: v12.19.0

macOS: Big Sur, 11.0.1

**Comment by Cito** [comment]
Commas in file names work fine for me. Maybe you haven't installed the latest version?

The README really needs better instructions for how to update to the current version when you already installed it earlier. I think what you need to do is `git pull; npm i; npm run build; nmp link`.

**Comment by repetitioestmaterstudiorum** [comment]
Hi @Cito, thanks for your fast response.

Just to be sure we're talking about the same thing: the comma is in the title of my evernote note, and not in the file name of the export of that note. 

Assuming we are talking about the same thing; I am wondering if it could be an edge case due to having "**" at the beginning of the title of the note? (which is markdown syntax)

Version: I did not install yarle. I ran npx. Does npx not use the latest version?

**Comment by Cito** [comment]
Yes, I tried with asterisks and comma in the title. The asterisks were converted to underscores (because they are not valid in file names) and the comma was left as it is.

If you use npx then you may use some older version installed in the cache, or at best the last published version which is not current either. There have been several fixes in the last time which have not yet been published. Therefore I always install the lastest version from the master branch using the steps above.

**Comment by repetitioestmaterstudiorum** [comment]
Alright, then I think this issue can safely be closed. Next time I will use yarle, I'll install it to make sure I'll use the newest vesion.
Thanks!

**Comment by tritola** [comment]
I am having the same issue as @repetitioestmaterstudiorum, converting a bunch of notes in one notebook, and all the notes with commas in the title have the commas replaced with the word "undefined" after conversion.

I used npx, but the version used is 3.5.2, which seems to be the newest version, released 21 hours ago.

Any thoughts what might be the issue, or how to go about fixing it?

Command I ran: npx -p yarle-evernote-to-md@3.5.2 yarle --configFile ./config.json
Node version: v14.15.4
macOS: Catalina, 10.15.7

**Comment by akosbalasko** [comment]
Hi @tritola ! 

Thanks for the detailed bug report. Could you please provide an enex file that does not work for you? 
Thank you!

**Comment by tritola** [comment]
Hi @akosbalasko and thanks for the quick reply!

Sure thing, I just ran another test with the attached test file, and same thing happened. I zipped the file, since .enex could not be attached.

[Test-notebook.enex.zip](https://github.com/akosbalasko/yarle/files/5783064/Test-notebook.enex.zip)

**Comment by akosbalasko** [comment]
Hi @tritola ,

Thanks for your example, I checked it and found that the enex file itself contains 'undefined' within the title. So the problem is around Evernote. Here is the proof, this is the relevant part from the enex: 

```xml
<en-export export-date="20210207T172602Z" application="Evernote" version="10.5.7">
  <note>
    <title>Test 2undefined a note</title>
    <created>20210107T172522Z</created>
    <updated>20210107T172537Z</updated>
```
Btw as I see you are using the latest (or almost the latest) version of Evernote. I checked it with the legacy version and titles with commas are exported correctly from there: 

```xml
<en-export export-date="20210107T221244Z" application="Evernote" version="Evernote Mac 7.14 (458244)">
<note><title>Some, thing</title>
``` 
So I would suggest exporting your notes from the legacy Evernote, and use Yarle on them.

**Comment by tritola** [comment]
Oh, that's interesting, didn't even occur to me to check that. Thank you for your help!

**Comment by artmg** [comment]
For what it's worth, this is still an issue with Evernote client 10.8.5 - Evernote don't seem in a hurry to fix their issue. Shame not everyone is as quick as @akosbalasko at fixing stuff :smile:
