### ISSUE TITLE
Not loading export template

### ISSUE THREAD

**Issue by larsbendixen** [akosbalasko/yarle#154]
Not sure if the problem is from my end. 

Here is my config.json: 
```
{
    "enexSource": "/Users/thinkforward/Dropbox/vault/notes/evernote_export/images.enex",
    "templateFile": "/Users/thinkforward/development/yarle/export_template.txt",
    "outputDir": "/Users/thinkforward/Dropbox/vault/notes/evernote_export",
    "keepOriginalHtml": false,
    "isMetadataNeeded": true,
    "isNotebookNameNeeded": false,
    "isZettelkastenNeeded": true,
    "plainTextNotesOnly": false,
    "skipLocation": false,
    "skipCreationTime": false,
    "skipUpdateTime": false,
    "skipSourceUrl": false,
    "skipWebClips": false,
    "skipTags": false,
    "useHashTags": true,
    "outputFormat": "ObsidianMD",
    "skipEnexFileNameFromOutputPath": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
}
```
Here is my export template:

```
export const defaultTemplate = `{title-block}# {title}{end-title-block}
{tags-block}
---
Tag(s): {tags}
---
{end-tags-block}
{content-block}{content}{end-content-block}
{metadata-block}
{created-at-block}    Created at: {created-at}{end-created-at-block}
{updated-at-block}    Updated at: {updated-at}{end-updated-at-block}
{location-block}    Where: {location}{end-location-block}
{source-url-block}    Source URL: {source-url}{end-source-url-block}
{notebook-block}    Notebook: {notebook}{end-notebook-block}
{end-metadata-block}
`;
```

After: 

```
npx -p yarle-evernote-to-md@latest yarle /config.json
```
Terminal output was:

```
Loading config from /Users/thinkforward/.npm/_npx/24360/lib/node_modules/yarle-evernote-to-md/dist/../config.json
Converting notes in file: /test/data/test-template.enex
Could not convert /test/data/test-template.enex:
source Enex file does not exists
(node:24561) ExperimentalWarning: The fs.promises API is experimental
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/test/data/test-template.enex'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

Thanks in advance.

**Comment by akosbalasko** [comment]
Hi @larsbendixen !

There should be a point before /config and it's extension must be json, not txt.

So, please rename your config file to config.json, and type the following in the folder where your config is located :

npx -p yarle-evernote-to-md@latest yarle ./config.json

Cheers,
akos

**Comment by larsbendixen** [comment]
Much thanks. I had a feeling it was my problem. Cheers.

**Comment by larsbendixen** [comment]
Thanks for your help. 

I only had the template with  a ".txt" extension (the docs said it didn't matter what extension you used?).

"There should be a point before /config"

Yes, ok, I knew I was probably missing something basic. 

"it's extension must be json, not txt."

But the file was already .json, so I didn't change anything there.

Run 

``npx -p yarle-evernote-to-md@latest yarle ./config.json`` 

and it gives me the same error. 

``Loading config from /Users/thinkforward/.npm/_npx/5915/lib/node_modules/yarle-evernote-to-md/dist/../config.json
Converting notes in file: /test/data/test-template.enex
Could not convert /test/data/test-template.enex:
source Enex file does not exists``

Appreciate the help. Can't wait to throw down this rope ladder. 

Lars

**Comment by akosbalasko** [comment]
Hi @larsbendixen !

Ok, it says that "/test/data/test-template.enex" what is specified as Enex source in the config.json does not exists. 
So, in order to convert your enex file instead, please edit config.json in your folder and replace "/test/data/test-template.enex" with the absolute path of your enex file. 
For instance if you place your enex file in folder 'noteFolder' within your user folder and it's named to 
"myNotes.enex", then your correct absolute path should be "/Users/thinkforward/noteFolder/myNotes.enex".
Then pls save your config.json and run the converter again by `npx -p yarle-evernote-to-md@latest yarle ./config.json`

**Comment by larsbendixen** [comment]
Hi Akos, 

Thanks for keeping at this with me. 

"Ok, it says that "/test/data/test-template.enex" what is specified as Enex source in the config.json does not exists."

Yes! This is what was weird to me. Because I have never typed those characters in my life. I don't know where "/test/data/test-template.enex" is coming from. 

So, I looked at my config.json. Here is now. I assure you, my absolute paths are correct. 

``{ 
"enexSource": "/Users/thinkforward/images.enex",
  "templateFile": "/Users/thinkforward/development/yarle/export_template.tmpl",
  "outputDir": "/Users/thinkforward/Dropbox/vault/notes/evernote_export",
  "keepOriginalHtml": false,
  "isMetadataNeeded": true,
  "isNotebookNameNeeded": false,
  "isZettelkastenNeeded": true,
  "plainTextNotesOnly": false,
  "skipLocation": false,
  "skipCreationTime": false,
  "skipUpdateTime": false,
  "skipSourceUrl": false,
  "skipWebClips": false,
  "skipTags": false,
  "useHashTags": true,
  "outputFormat": "ObsidianMD",
  "skipEnexFileNameFromOutputPath": false,
  "monospaceIsCodeBlock": false,
  "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
     }
}``

That is what is confusing to me: I have not configured "/test/data/test-template.enex" anywhere. I have no reason to do so. 

Thanks again!

**Comment by Cito** [comment]
The `/test/data/test-template.enex` is in the default configuration file. Your output shows that Yarle is still loading the config from the npm cache, where it only finds the default configuration, it is not loading the configuration from your working directory.

Older Yarle versions used to do behave like that, but since you added `@latest`, you should be using the latest one, which should work properly. Maybe @akosbalasko has an idea what could be the problem here.

**Comment by akosbalasko** [comment]
Hi @larsbendixen, hi @Cito !
I think I finally get it.
Unfortunately, I wrongly cited the command to be executed in my previous commend. I'm sorry!

The readme says this:
`npx -p yarle-evernote-to-md@latest yarle --configFile <path_to_your_file e.g. ./config.json>`

So, --configFile is missing before ./config.json . It is really mandatory because this '--configFile' is recognized as the command has a config argument. Otherwise, it falls back to the default config, as we see. 
So the correct command should be:
`npx -p yarle-evernote-to-md@latest yarle --configFile ./config.json`

**Comment by Cito** [comment]
> So, --configFile is missing before ./config.json

Whew! We were probably so focused on the path itself that we didn't notice the missing option. Good catch 😅

**Comment by akosbalasko** [comment]
I missed it at first too, then I had to check the code to have a clue how it does work :D

**Comment by larsbendixen** [comment]
Hi @akosbalasko and @Cito,

Nice! 

``Conversion finished: 66 succeeded, 0 skipped, 0 failed. Total notes: 66``

This is a really useful tool. Thanks for your help!

**Comment by larsbendixen** [comment]
Hi @akosbalasko and @Cito,

``Notes processed: 1447
Conversion finished: 1447 succeeded, 0 skipped, 0 failed. Total notes: 1447``

Thanks for the help! @akosbalasko this is a really useful tool.
