### ISSUE TITLE
No Xcode or CLT version detected!

### ISSUE THREAD

**Issue by tokeriis** [akosbalasko/yarle#158]
Am I correct in interpreting this error message as I need to install Xcode for this to work?
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tre/.npm/_npx/39420/lib/node_modules/yarle-evernote-to-md/node_modules/utimes
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utimes@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utimes@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by akosbalasko** [comment]
Hi @tokeriis !
Yes, you're right. Unfortunately utimes requires building its package on-site, therefore it needs node-gyp to do it. As a fortune, utimes was introduced 12 days ago to set creation date of the notes to the date on what the Evernote note was created. In order to keep no-install, I reverted this change and released a new version until utimes supports pre-built packages. 
In order to use the latest version that does not need any xcode dependency, please simply type the same command again: 
`npx -p yarle-evernote-to-md@latest yarle --configFile <path_to_your_file e.g. ./config.json>`

Thank you for raising this issue up! 🥇

**Comment by tokeriis** [comment]
Thank you for a very quick fix. It seems to work like a charm.
