### ISSUE TITLE
Yarle hangs on  large .enex file

### ISSUE THREAD

**Issue by seatrout** [akosbalasko/yarle#204]
I have a file of >4000 evernote clips made from the web, and Yarle hangs processing one of them. I can't isolate which one, since it is helpfully called "untitled note" and there are something like 40 of those. I could send you a .zip of the whole thing -- it is simply news stories of one sort or another clipped over the last 15 years -- but is there a more helpful way to do divide them?

**Comment by akosbalasko** [comment]
Hi @seatrout !

It looks like that the root cause is the same as reported by you before, currently, I'm working on it.
What I found is that a webclip can have a really complex structure in HTML and the 3rd party dependency what I use for parsing HTML DOM hangs. I'm thinking on a solution, a possible workaround would be to remove the empty divs (in the last example you shared me contains huge amount of divs with inline css like:
```html
<div style="-moz-binding:url(&quot;about:abp-elemhidehit?810520334591#dummy&quot;);z-index:1010;overflow-x:hidden;overflow-y:hidden;min-height:74px;text-align:center;background-color:rgb(246, 246, 246);float:right;" />)
``` 
I try this option, and brainstorm something else if it still cannot be parsed. 

Sorry.

**Comment by seatrout** [comment]
throwing out all empty divs seems to me a good idea irrespective and I completely approve this plan.

**Comment by akosbalasko** [comment]
Hi @seatrout ,
The new version is out, please execute Yarle again as you did it before, it will load the latest version. 
Hope it won't hang anymore. 
Any feedbacks are welcome!
