### ISSUE TITLE
Feat: Support Evernote 10+

### ISSUE THREAD

**Issue by akosbalasko** [akosbalasko/yarle#218]
As among several things the exported xml format changed in EN 10+ ,  it would be great if Yarle could support those enex files too.

**Comment by tokeriis** [comment]
One problem I have is that I use an Applescript to batch export all notebooks in one go. This works nicely with Evernote 7 for Mac but It seems Applescript is still not supported in Evernote 10, and may never be. It is not on the list of features promised by EN developers, and since the idea with version 10 was to free Evernote from platform specific features, I find it unlikely.

This makes me think that YARLE might go a step further and siphon the enex files directly from Evernote as part of the conversion process, using a cross platform script. This would of course benefit not only Mac users.

**Comment by waugh2k** [comment]
I just found YARLE and am trying to port my Evernote collection into Obsidian. I'm running 10.16-7.  Is it not supported?  Also, IOS won't let me open the YARLE app because of its source.  And the latest version of IOS provides no option for allowing it.  Does that mean that I'd have to compile it myself?  I feel so near and yet so far!

**Comment by akosbalasko** [comment]
Hi @waugh2k ! 
Yes, Yarle supports Evernote 7.xx (or older) only, it's because in EN 10+ they made some essential changes and introduced a note-limit for export which lead me to still not do more effort on supporting that versions. But they provide the legacy version, so I would suggest downloading the legacy one in where you can export all of your notes with no limit. Here it is: https://cdn1.evernote.com/mac-smd/public/EvernoteLegacy_RELEASE_7.14.1_458325.zip

About opening Yarle: as far as I know a right-click on the icen and clicking to 'open' on the pop-up menu should result the same error window but with an extra button that allows you to ignore the source-checking and open it anyway.

**Comment by waugh2k** [comment]
Many thanks. I also learned that Joplin is a way to convert ENEX to markdown. Can I pull from Joplin into YARLE?  I’m really excited to use this to try Obsidian, because I have @14k notes and Evernote seems to be less useful with every build.  I’m going to go ahead and stop my export from Evernote now and install the legacy program (thanks for the link!).  I’ll get through this eventually!

cheers
John

Sent with a Spark

**Comment by akosbalasko** [comment]
Joplin has an internal importer that can be used for conversion from Evernote, but I've heard from many that Yarle provides a greater set of options on how the notes should look like, Yarle creates notes based on the creation dates while Joplin does not support this, etc. So in the aspect of the conversion of EN notes, Joplin is identical with Yarle. 

If you decide to give Yarle a try, I'm here to help. 14k is a huge amount btw :) 

Cheers,
akos

**Comment by medmunds** [comment]
FWIW, I'm using Evernote Mac 10.17.6, and had no trouble exporting enex files with 140+ notes—which is more than [Evernote's documented 50 note limit](https://help.evernote.com/hc/en-us/articles/209005557-Export-notes-and-notebooks). (I'm guessing that help article is outdated.)

Also, so far the Yarle conversion to Markdown seems pretty good: from what I can tell, Yarle _does_ support Evernote 10 enex files. (I haven't read through every single document, but I checked a bunch of them. With the exception of the newer checklist format—PR #278—I didn't see any obvious problems specific to Evernote 10.)

**Comment by akosbalasko** [comment]
Hi @medmunds ! 
 
 Wow, that's good news, I retest it soon with the new version of EN. 
 AFAIR the embedded pictures' syntax was changed... or something like this. Anyway, if this note limitation is released now, it opens the gates to focus more on EN10, until this time it sounded meaningless for me. 
 Thank you for the insights!

**Comment by medmunds** [comment]
> the embedded pictures' syntax was changed... or something like this

Ah, it seems like the EN web clipper captures some images (at least SVG) using data urls: `<img ... src="data:image/svg+xml,...">`. And that gets converted to Markdown as `![svg%3e](data:image/svg+xml,...)`, which doesn't render properly—and leaves a huge blob of raw image code in the markdown.

I'll see if I can spot an easy fix, or else open a new issue with a sample enex.

(EN10 still also uses `<en-media hash="...">` for other images, and those seem to convert OK.)

**Comment by medmunds** [comment]
Potential fix for data-url images in #285

**Comment by akosbalasko** [comment]
As the dependent story has already been merged and released in v 4.2.2, I think EN 10 is supported.
