### ISSUE TITLE
feature req.: Save Desktop App Configurations

### ISSUE THREAD

**Issue by grantx2016** [akosbalasko/yarle#256]
Great work on the ongoing development with Yarle!

I really like the Desktop App. It appears to work fine except for one thing .. my configurations are not being saved after I quit the app and reopen it. Is this normal?

**Comment by akosbalasko** [comment]
Hi @grantx2016 , yes, that's normal, storing the config is not supported yet, but it's definitely a valid request, so let me label it as 'enhancement', and plan with it in the roadmap.

**Comment by grantx2016** [comment]
Cool. Thanks @akosbalasko 👍

**Comment by jmtornetta** [comment]
Aren't the config files stored in the program's user files? On Window's I was able to find from ~/AppData/Roaming/....

**Comment by Tokolino** [comment]
Thats a feature thats really great! I thought that I could mimick it by editing the config.json file, but that does not help either. If you have to find out what the individual parameters do, actually, and which work best, it's always a hassle to reenter those that you had before.

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
Thanks for raising this story up, I implemented and released it in version 5.9.0. 
Now the conversion stores the current config file in the root folder of the output directory in a file called 'yarle.config'. Then it can be loaded by clicking on a brand-new button 'Load config' at the top of the configuration tab. 
Please note that currently the next execution overwrites the config file, so please makes sure that you create a bckp from the config if you would like to keep it in a long term. I'll improve the solution by adding a timestamp at the end of the file, and use the latest one in order to keep all configs over time. 
Cheers,
akos

**Comment by Tokolino** [comment]
Thanks @akosbalasko !
However - it seems to be that the yarle.config file is not plain text. I thougth that it would be json as well, so I could check the configurations in the file. I am now starting to convert my notebooks to Obsidian, and I am still checking the effect of different options, and then it would be helpful if I could see them directly in the file.

Warm regards, Thorsten

**Comment by akosbalasko** [comment]
Hi @Tokolino , 
Yes, it is a base64-encoded version of the config json, which would be a plain text, I mean a human readable config file. I encoded it just to prevent manual changes, because otherwise the output format could be changed to something that is not even recognizable by Yarle, that could lead troubles. But yes, I didn't consider this scenario what you mentioned, to check the changes of different options and compare the config "manually", I agree with it. 
So, with the improvements of the multiple config savings I'd remove the base64 encoding. It comes hopefully today.

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
I released the changes in version 6.0.0, please check it out: https://github.com/akosbalasko/yarle/releases/tag/v6.0.0

**Comment by Tokolino** [comment]
How great that Notepad++ supports BASE64 decoding, so I could reuse the yarle.config file from the previous version :-)
However, it seems that the option "Convert Web Clips" is not saved - I always have it to switch to "yes" manually.
