### ISSUE TITLE
Seperation line replacement is not working

### ISSUE THREAD

**Issue by guoboism** [akosbalasko/yarle#301]
Seperation line  is still *** in the output even though I set it to ---

Windows v4.1.0

**Comment by akosbalasko** [comment]
Hi @guoboism ,
Where did you set this separation line? In the template?

**Comment by guoboism** [comment]
Below are some screenshort of this problem, test in win10 with 4.1.1

![image](https://user-images.githubusercontent.com/705499/130014454-268223c6-86b2-4be0-b0e2-160c8ad7a7cc.png)

![image](https://user-images.githubusercontent.com/705499/130014360-d181ae09-4d86-4713-a03a-46b5018558dc.png)

![image](https://user-images.githubusercontent.com/705499/130014496-5062c71a-f3cf-48b1-88ca-e15aae6ebd49.png)

![image](https://user-images.githubusercontent.com/705499/130014430-6c9bde0f-fd06-40b9-a7ba-68dd7254e692.png)

**Comment by akosbalasko** [comment]
The --- you changed is for separating the nested tags, for instance if you have tag1/tag2 as a tag in EN, it will be transformed to tag1---tag2 . it looks like that these 111, 222 fields are simple texts, not tags, separated by horizontal line, which is 3 stars in md.

**Comment by guoboism** [comment]
@akosbalasko Thanks for clarification on this

*** does work as a seperator in logseq (--- work as well)
but * * * does not, it appears as
![image](https://user-images.githubusercontent.com/705499/130031977-c7c483a3-19eb-4256-96d7-692e3963e9b4.png)

So, it is still a problem. If  * * * is a standard that Logseq do not respect, I think you might as well just provide an option to set custome replacement for that.

**Comment by guoboism** [comment]
@akosbalasko You can leave it to me. I can fix this (by providing an extra option) and will sumbit PR when the whole logseq thing is done

**Comment by akosbalasko** [comment]
hi  @guoboism ,

* * * is in the standard Commonmark, so its not an Obsidian-specific element to generate horizontal lines.
Ok, but please try to abstract the possible differences among logseq and obsidian in order to allow to introduce other notetaking apps in the future. I mean that instead of simple conditions within the code, I woud prefer to setup complete languagesettings object for each supported apps, store everything that differs from the commonmark syntax, and use the proper properties in the code. Hence only one setting is required in the UI: which dialect do you want to use, Logseq or Obsidian. And then it can be extended easily in the future. 
Thank you!

**Comment by akosbalasko** [comment]
Pls create a new issue for that instead of changing the title of this, because it will mess the things up. Thank you!
