### ISSUE TITLE
Notes failing to convert; says it suceeded

### ISSUE THREAD

**Issue by NAL100** [akosbalasko/yarle#358]
I haven't been able to have any of my notes convert successfully. Yarle creates the directories, exports the resources, but there are no markdown files. I'm using the Mac OS X binary.

Here is a sample error:

Conversion started at Thu Feb 17 2022 23:46:38 GMT-0500 (Eastern Standard Time)
Converting note "Untitled Note"...
Failed to convert note: Untitled Note, {"errno":-2,"syscall":"scandir","code":"ENOENT","path":"/Users/Admin_1/Evernote export/notes/@Inbox/_resources"}
Conversion finished at Thu Feb 17 2022 23:46:38 GMT-0500 (Eastern Standard Time)
Note "Untitled Note" converted successfully in 0.014 seconds.
Notes processed: 3

Then I get something like this at the end:

Conversion finished: 28 succeeded, 1 skipped, 0 failed. Total notes: 29

I'm not sure why it would say it was successful when the note wasn't exported; also why a note was skipped?

**Comment by akosbalasko** [comment]
Hi @NAL100 ,
I'm really sorry, I missed to response your question.
The misleading calculation looks like a valid bug, I'd investigate it further, but I think I have a clue why the note has been skipped: It may happen because of the "@" sign in the folder. Could you please try to remove the @ from the Inbox name in Evernote, export the notebook and try to do the conversion again to confirm? 
Thank you, and sorry again for this huge delay.

akos

**Comment by NAL100** [comment]
> Hi @NAL100 , I'm really sorry, I missed to response your question. The misleading calculation looks like a valid bug, I'd investigate it further, but I think I have a clue why the note has been skipped: It may happen because of the "@" sign in the folder. Could you please try to remove the @ from the Inbox name in Evernote, export the notebook and try to do the conversion again to confirm? Thank you, and sorry again for this huge delay.
> 
> akos

Hi akos,
Thanks for getting back to me. I appreciate all of your work on this project and for your responsiveness within the community. I eventually got this to work after a bunch of research on the "scandir" error. I tried a lot of things but I think it was because of something within node.js? I don't remember why (honestly I was trying to fix multiple apps at the same time) but here is what I ran in my command line:

```
npm install
npm install -g npm@8.5.2
node i
npm run gulp serve-static
npm audit fix
```

As it turns out the @ signs did not need to be removed, and I'm still not sure why the Yarle output was succeeded. Also something I still have not figured out is that some of my notes were "skipped" and there's no record in Yarle of why they were skipped or even which files they were. For the most part I found that it worked quite well to get the notes exported, so thank you. Also I echo the feature request in #233 since I would have preferred tags in front matter but ended up settling for them being in the content of the note due to functionality.

**Comment by montemartin** [comment]
I can confirm that the incorrect error reporting is an issue. I've been trying to convert ~2800 notes across 7 notebooks. I'm getting ~100 total failures, but none of them have any output as to the reason and they all say converted successfully. Here is an example: 

```
Conversion started at Thu Mar 03 2022 14:33:31 GMT-0600 (Central Standard Time)
Converting note "New Client Project Setup"...
Failed to convert note: New Client Project Setup, {}
Conversion finished at Thu Mar 03 2022 14:33:31 GMT-0600 (Central Standard Time)
Note "New Client Project Setup" converted successfully in 0.004 seconds.
Notes processed: 184
```
At the end of each notebook I'm getting output like `Conversion finished: 209 succeeded, 0 skipped, 0 failed. Total notes: 209` even though there are clearly failures. 

I'm also stuck on what is causing those notes to fail. Resource folders are created for those that contain images/PDFs, but there is no note. I'm going to try to collect a complete list of notes that failed and go back to Evernote so see if I can find out what the issue is.

**Comment by montemartin** [comment]
I've narrowed down some of my issues. For me there are two: older todo items and extra long titles aren't converting. However it looks like there are still some .md notes unaccounted for once I adjust for that. 

I have 2827 total notes in Evernote. When I sum the values of `Conversion Finished` from the conversion log of all exports I get exactly that number, so I know it's processing all the notes. But when I look in the output folders I have a total of 2660 .md notes generated - difference of 167 notes. 

Pulling all the `Failed to convert note:` from the conversion log only showed 108 failures. 103 of those were the older todos. I generated an older .enex of all todo items and got exactly the same results. Of the remaining 5 failures 3 of them have output explaining why they failed, leaving 2 unexplained failures. 

But I'm still at a loss how to ID those 59 other missing notes.
