### ISSUE TITLE
Yarle failed output of big data

### ISSUE THREAD

**Issue by Oblique82** [akosbalasko/yarle#374]
Hi

I tried to export a 7gb enex. with 5000 notes

anyway YARLE log reported it was finished but the data didn't output to the folder I specified. 

I can still hear the fans spinning up and yarle is using CPU for something

is there a 'temp' location where yarle puts the data before moving it to the final output directory?

I am on Macos big sur

thanks

**Comment by akosbalasko** [comment]
Hi @Oblique82 !
Thank you for reporting this issue! 
It's quite strange for me, there is no temp folder, because Yarle reads and writes data as a stream, so the output files should be in place right after it logs the success message in the UI. 
About the delay: a second hidden phase of the conversion is the application of the inter-enex links, which is done sequentially after the conversion. It checks all the files generated and replaces the links to notes from other enex notebooks, and as we are talking about huge number of notes and 7gb, it may take some time, so this behaviour can be the cause of the fan-spinning. 
Could you please send me the output log generated? And pls double check that you have enough space in your drive and such primary possible causes? 
Thank you very much!

**Comment by Oblique82** [comment]
thanks for the reply I have 300gb free. I have had a few instances with small enex files where the stream does not write to the designated location. unfortunately I didn't keep the log after I had to quit the app but it reported no errors (5000files apparently worked but no output)

**Comment by akosbalasko** [comment]
@Oblique82 do you use Yarle via command line, or with its UI? 
No output means no md files neither, nothing, or the attachments are missing?

**Comment by Oblique82** [comment]
Correct no output at all. This was with the electron gui package

**Comment by akosbalasko** [comment]
@Oblique82 , it looks like a silly question, but do the notes contain checkboxes? I ask this, because there is an other strange issue around checkboxes, yarle reports they are converted successfully, but there are no notes placed in the filesystem. 
Could you pls reconfigure Yarle and send me the config? it is logged right after the start of the conversion. 
Thank you very much!

**Comment by akosbalasko** [comment]
@Oblique82 and one more question: from which version of Evernote do you export your notes?

**Comment by Oblique82** [comment]
10.35.3 currently

**Comment by akosbalasko** [comment]
@Oblique82 how does it work, if you export your enex files via the legacy Evernote app (7. something) ?
