### ISSUE TITLE
YARLE should have a feature to remove characters from note titles that might conflict with Obsidian

### ISSUE THREAD

**Issue by Nvno23** [akosbalasko/yarle#425]
Hi, 

First of all thank you for creating such an awesome tool, it made the transition from Evernote into Obsidian way easier. 
I have a peculiar case for you. I work in IT, and most of my notes are of incidents and requests I worked on. My way of work was always to place a status in my note title, such as [SOLVED] or [TRANSFERRED],  to indicate what happened to the ticket I was working on. 

When transferring a folder from Evernote into Obsidian, I noticed that much of my notes had broken links between the note and its attachments. Could it be because of the way Obsidian interprets square brackets? If so, my only course of action would be to go into each note one-by-one and remove the brackets from my notes in Evernote, before using YARLE. I have nearly 6 thousand notes in this situation.

Is it possible that to include a feature in YARLE to remove "problematic" characters from Evernote's note titles before creating them in Obsidian? Just to make sure that no conflicts happen?

I'm looking forward to your feedback on this.
Thanks in advance.
Kind regards

**Comment by akosbalasko** [comment]
Hi @Nvno23 ! 

Good point, currently the file names( which are shown as file titles in obsidian) are sanitized with default os-related characters, just to be able to save the file at all. 

This, what you're raising up, is an absolutely good and fair point, I'd be glad to implement it soon. Unfortunately it will take some days from now, because my machine gave up the fight, so now i don't have anything to work  on. But it will be solved hopefully during this week, once I have the new one, this will be the first feat to be implemented.

**Comment by Nvno23** [comment]
Hi Akos,

Thank you for your quick response. There is no need to rush. My notes are
still accessible via Evernote so please take your time.
It will be a really great feature to have, considering that Evernote lacks
any sort of find and replace tool.

Best regards!


Akos Balasko ***@***.***> escreveu no dia segunda, 28/11/2022
à(s) 14:22:

**Comment by akosbalasko** [comment]
Hi @Nvno23 ,

I added the needed normalization, and now all of the characters, namely [ ] | # ^ will be removed from file names. 
Take a look at it, thank you for raising this up! 
If something still doesn't fit, don't hesitate to create a new issue.

**Comment by Nvno23** [comment]
Hi Akos,

I’ll be sure to try it out later.

Thank you for taking your time to address such a specific issue.

Best regards
