### ISSUE TITLE
YYYY-MM-DD format outputs as yyyy-22-Th

### ISSUE THREAD

**Issue by filmgal** [akosbalasko/yarle#468]
I have the date format set to YYYY-MM-DD

My template includes: 

{created-at-block}datecreated: {created-at}{end-created-at-block}
{updated-at-block}datemodified: {updated-at}{end-updated-at-block}

The output for this note should be:
datecreated: 2018-04-06
datemodified: 2018-03-26
which are the Evernote dates.  

Instead I get:

datecreated: yyyy-22-Th
datemodified: yyyy-07-Mo

**Comment by akosbalasko** [comment]
Hi @filmgal !

Sorry for the delay. I double-checked it, and it looks like that your date format was not set as capital letters. If I set the date format to yyyy-mm-dd, it won't be a valid format, that's why we get y-s in the output.

But if you set it to YYYY-MM-DD (or leave it as it is since this is the default format), then as I see, Yarle produces the correct output. 
Let me close this issue, but feel free to comment here below if you still have the issue, and we will check it out.
