### ISSUE TITLE
Frozen while converting Enex file

### ISSUE THREAD

**Issue by NathanSkene** [akosbalasko/yarle#48]
Hi,

I'm trying to move from Evernote to Obsidian. I came across this in the Obsidian forum. I exported all my notes from Evernote to an Enex file. Then I set this running with:

`npm run start -- --enexSource="/Users/natske/OneDrive - Imperial College London/Evernote Export/My Notes2.enex" --outputDir=./out --include-metadata --zettelkasten --outputFormat=ObsidianMD`

It ran fine through the first 2675 notes then just stopped and didn't progress any further. 

<img width="281" alt="image" src="https://user-images.githubusercontent.com/33265555/93455921-e3fd3980-f8d4-11ea-8eb5-25e1bb914403.png">

So it's been looking like that for 30 mins. Is there a debug log I could look in? 

Thanks for developing this!

**Comment by akosbalasko** [comment]
Hi @NathanSkene ! 
Thanks for trying Yarle! It should not stop anywhere, I run some heavy stress-tests against it and they were passed. Unfortunately, no debug logs. But as it converts notes one by one, the problematic one should be "Background genes". Could you please export and convert only that one? Just to see that the problem is not around the amount of the notes. And please check if is there any specific in that note, pdf attached or something. 
Thank you!

**Comment by NathanSkene** [comment]
I'd figured it was 'Umbrella'... hadn't read it properly.

Turns out 'background genes' doesn't even open in evernote properly. It's
an absolutely massive single column table.

Have attached it to this email but this might be to specific a bug to
bother fixing!

**Comment by akosbalasko** [comment]
Could you please send it as an attachment to my personal address? it's akos0215@gmail.com .
Unfortunately github does not handle well the attachments. 
Thank you very much!

**Comment by akosbalasko** [comment]
Hi @NathanSkene ! 
I was able to reproduce this issue, and it looks like that the problem appears in a 3rd party dependency. I try to resolve that on my own, and/or raise this stuff on their git board. Whenever we have a solution, I'll update you.

**Comment by nikiluk** [comment]
I confirm that some of the notes convert significantly longer than others. For example, this note took me almost 10 minutes to convert.
![2021-01-11 23 58 34 npm](https://user-images.githubusercontent.com/6605974/104255651-3b29aa00-5482-11eb-96c7-ecf0bff93b13.png)

**Comment by akosbalasko** [comment]
@nikiluk , does this note have some exceptional property? I'm mean, does it contain many attachments, large texts, or anything?  
And it is finished, right?

**Comment by nikiluk** [comment]
Hi, yes finished. I did a small add to check the outliers in terms of conversion time. I can also commit my couple of lines change, so that it could be easier to identify issues.

> Finished conversion: Wed Jan 13 2021 17:05:55 GMT+0200 (Eastern European Standard Time)
> Note "coach.pocketconfidant.com | Website Review for coach.pocketconfidant.com | WooRank.com" converted successfully in **418.754 seconds.**
> Notes processed: 4

**Comment by akosbalasko** [comment]
Hi @nikiluk ! 

Thank you for your tests, it takes more time on my machine :) So, as I see the problem is around the parsing and the conversion of HTML to MD. I use turndown for this, I see a discussion about the performance on their side, but I'm not sure they will fix it soon, hence I'm thinking on replacing turndown to something similar but faster.
