### ISSUE TITLE
Javascript Uncaught Exception Permission Error on start

### ISSUE THREAD

**Issue by david-heasman00** [akosbalasko/yarle#480]
Hi there, 

I'm on MacOS Ventura 13.3.1 (a) on an M1 Pro. 

Yarle-to-md GUI gives me a Javascript permission error when I try to run it. This issue started after I installed a script that uses yarle. I've since uninstalled the script, and uninstalled any packages related to the script, yet the issue persists. I've uninstalled yarle, and re-installed it several times and it still persists. 

Any tips to resolve this issue? I'm going to try uninstalling node entirely and see if that fixes it. 

Uncaught Exception:
Error: EACCES: permission denied, open '**<user directory>**/Library/Application Support/yarle-evernote-to-md/conversion.log'
at Object.openSync (node:fs:594:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
at Object.writeFileSync (node:fs:2207:35)
at Object.appendFileSync (node:fs:2269:6)
at loggerInfo (/Applications/yarle-evernote-to-md.app/Contents/Resources/app.asar/dist/utils/loggerInfo.js:57:8)
at IpcMainImpl.<anonymous> (/Applications/yarle-evernote-to-md.app/Contents/Resources/app.asar/dist/ui/main.js:60:7)
at IpcMainImpl.emit (node:events:513:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80718)
at EventEmitter.emit (node:events:513:28)

**Comment by akosbalasko** [comment]
Hi @david-heasman00 ,
I think the problem is that Yarle is copied to among the other applications. (which is an important folder requiring more privileges to write into it). I suggest to move it back to the Downloads folder, and it should work correctly. 
If you wish to keep it there, you can add extra permissions to the app by following the next steps: 
If you right-click on Yarle and click 'Get Info' on the appearing modal window, you will get a window popping up with details about the application. Down below there is a section in where you can set the privileges needed by the app (see the picture), and select read&write. 

<img width="395" alt="Screenshot 2023-06-19 at 21 13 36" src="https://github.com/akosbalasko/yarle/assets/11886731/b9012d19-4687-4639-8ec9-05933b2f1c83">

Cheers,
akos

**Comment by david-heasman00** [comment]
That...that makes sense. Should've seen that. Will try that now and report back.

**Comment by david-heasman00** [comment]
Dang, still doesn't work. Kept it in the downloads folder, and changed read/write permissions as instructed. Still get the same error: 
<img width="1268" alt="Screenshot 2023-06-20 at 10 13 46" src="https://github.com/akosbalasko/yarle/assets/1979286/691a688b-61d7-46b4-ad12-36c6e6976ac4">

**Comment by akosbalasko** [comment]
That's strange, it still wants to put the conversion.log under the Library/Application Support/... folder. 
What if you change the owner of the folder? 
Open a terminal and type the following: 
```sudo chown -R $USER /Users/david.heasman/Library/Application Support/yarle-evernote-to-md```

**Comment by david-heasman00** [comment]
I'll be damned. That works. I honestly have no clue how the script I ran broke things, but lesson learned – don't run 3rd party scripts unless you know what you're doing. 

Source of the script here https://github.com/dmuth/evernote-to-obsidian
