### ISSUE TITLE
Link to renamed Evernote gets broken after conversion

### ISSUE THREAD

**Issue by rijnb** [akosbalasko/yarle#482]
If you links to an Evernote document and renamed it later, the name of the link in Evernote does not get renamed. Internally, the correct URI is used, however. But in the conversion process the old document is used. (Because it cannot resolve the new name from the `evernote://` URI, probably, only from the link name - which was not renamed).

**Comment by akosbalasko** [comment]
Hi @rijnb ,
Thanks for raising up this issue! Unfortunately, I don't think it can be resolved, because afair the links in the exported Evernote enex file are not represented as you expect, with direct and unique identifiers(like the evernote://....). The link appears in one note, but it isn't stored in the target note, the name of the source note is stored there only. Therefore I have no chance to identify the connected notes via links, but just by investigating the names. I think the same should happen if you export a renamed linked enex and then re-import it to another account.

**Comment by rijnb** [comment]
That's what I feared. I might try and create an issue for Evernote to add the correct title to the Enex file instead... Thanks for looking into this.

**Comment by rijnb** [comment]
(You can close the issue AFAIC.)
