### ISSUE TITLE
Indent is not preserved

### ISSUE THREAD

**Issue by kazukiotsuka** [akosbalasko/yarle#493]
One more thing to give up migrating from EN to Obsidian is **indent**.
In my sense, since many people around me organize logic through hierarchical structuring, this indent issue seems important.

**before**
![Screenshot 2023-07-21 at 12 08 49](https://github.com/akosbalasko/yarle/assets/3203107/becbc6f6-8f01-408d-b399-36093357a70f)

**after**
![Screenshot 2023-07-21 at 12 09 08](https://github.com/akosbalasko/yarle/assets/3203107/01e578aa-97f1-41b0-8d7a-a6e85006af98)

**Comment by akosbalasko** [comment]
Hi @kazukiotsuka 
By default Evernote indents the list items, but this indentation is not stored in the Enex file, just the list itself. I think the indentation should be specified by the target system, and I don't think that Yarle can do anything with it.

**Comment by kazukiotsuka** [comment]
@akosbalasko  I see. Is it the same for normal indentation as well as list indentation? In my team, 70% of the people use list indentation frequently and about 30% use normal indentation like python. Since the indentation drastically effects the layout, it is critical matter for deciding if we migrate or not.

**Comment by akosbalasko** [comment]
hi @kazukiotsuka ,
sorry for the long felay, I was on vacation. 

So, what would be the expected behavior? 
Convert EN  lists **with indentation** into Markdown? 
Which would be your target app to migrate into? Obsidian? 
According to the answer of these questions I could investigate the possibilities/ figure out a solution for you.

**Comment by kazukiotsuka** [comment]
@akosbalasko Thanks for reply. The target app is Obsidian. My expected behavior is to preserve any indentation into Markdown not only in the list but also normal indentation like:
![Screenshot 2023-08-04 at 9 48 04](https://github.com/akosbalasko/yarle/assets/3203107/635f2d7f-6250-445f-a7d9-57c1ff6aad66)
Me and people often arrange notes in this way so that I can't migrate if this structure not preserved.

**Comment by akosbalasko** [comment]
Hi @kazukiotsuka ,

Sorry for this long delay. Now I tested it and I think the problem is not related to Yarle, indeed its not a problem at all, it is the by-design behaviour of Markdown. Tabs or 4 spaces are recognized as indentation, and lists by default are not indented at all. 
So I'm afraid, if you would like to move out from Evernote and keep the indentation, you should consider other note taking applications that are not based on Markdown.
