### ISSUE TITLE
Another errornous image extraction...

### ISSUE THREAD

**Issue by Tokolino** [akosbalasko/yarle#557]
I have one note which translates to a weird image extraction behaviour. The image itself is extracted and named properly, but it's linking in the note is totally strange - I see parts of the image name, but also a Base64 encoding of the image. Very weird.

An export with this note is attached.
[Debug.zip](https://github.com/akosbalasko/yarle/files/13795537/Debug.zip)

**Comment by akosbalasko** [comment]
Ehh.. yeah, webclips, another solution for the same stuff, now it is a link ("A" in HTML), but it's href is the base64-encoded pure content of the image, while within the tag the innerHTML contains an en-media tag with the detailed properties of the given resource.
It will take a bit longer to solve, sorry for the inconviences.

**Comment by Tokolino** [comment]
Hi @akosbalasko,
unfortunately this problem got back with version 6.0.5...

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
Huh, okay, yes yes, it is still Open, I didn't solve it.

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
I fixed it in version 6.0.6.

**Comment by akosbalasko** [comment]
Hi @Tokolino ,
ehh, that's true. It is because these `embedded` images come from base64 image of the href attribute of a link tag, and as they don't have filename attribute or something else, I generated these `embedded`+index filenames.
While the others with the correct filenames are from the resource tags stored in a different place. The next step would be to check how they can be connected together.

**Comment by akosbalasko** [comment]
I think I found a workaround, released in v6.0.7
