### ISSUE TITLE
Support chunked enex files

### ISSUE THREAD

**Issue by Cito** [akosbalasko/yarle#75]
It seems that newer versions of Evernote split the notebooks in chunks when they are larger than 100MB, like `Notebook.enex`, `Notebook [2].enex`, `Notebook [3].enex`, ... It would be nice if Yarle recognizes when there are "follow-up" notebooks and imports their contents as if they belonged to the first notebook file.

**Comment by akosbalasko** [comment]
Hi @Cito ! 
Wow, I did not know this feature in Evernote. Which version introduced such behavior? When I exported really huge enex files, I got only one huge file, it was done by EN 7.14 afair.

**Comment by Cito** [comment]
Hi @akosbalasko - not sure in which version they started doing this. I noticed it in version 6.25 on Windows which is the latest version on Windows before version 10. Version 7.x exists only on Mac. Maybe only the Windows version of EN does this. I see no option to switch this off, it seems to happen automatically.

**Comment by akosbalasko** [comment]
Aham, so it looks like a platform-dependent feature. I'm pretty sure that these will be eliminated or reimplemented platform-independently, because EN currently standardize its different EN implementations and feature sets. 
One more thing that came to my mind: currently Yarle supports input folders as well, which means that every enex file within the given folder will be converted. It sounds that it meets to your request, as I see, right?

**Comment by Cito** [comment]
If you have local notebooks, you're stuck with the legacy versions of Evernote - they will not be supported by the new version.

Specifying the parent folder of the enex chunks is a good idea and kind of works. I say "kind of", because it produces separate output folders for each chunk, and you will get problems when there are duplicate note tiles and you try to merge them together.

Maybe a solution would be a "--merge" option that allows merging all the input files into one output directory, while properly taking care of duplicate titles (adding consecutive numbers to them across all the notebooks). That option might be generally useful for merging several notebooks together.

**Comment by akosbalasko** [comment]
Aham, ok, I think I get it. But instead of having --merge as config parameter (as yarle can resolve duplicated note titles by adding incremental index to the file name), I added --skipEnexFileNameFromOutputPath that makes yarle to use the same output folder for every Enex files, if a folder was given as input. This is the PR: https://github.com/akosbalasko/yarle/pull/83, but I'll release a version soon as well. 

Thank you @Cito for raising these issues, these are really inspiring and meaningful!

**Comment by Cito** [comment]
Thanks a lot for implementing this!

**Comment by Cito** [comment]
Just tried it out and I think this is a sufficitent solution for the problem with chunked Notebooks.

You should also document this option in the README.

**Comment by Cito** [comment]
`skipEnexFileNameFromOutputPath` Is now documented in README, so closing this.
